# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Gtk2-Phat
version:      0.02
version_from: pm/Phat.pm
installdirs:  site
requires:
    Gtk2:                          1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
